################################################################################################################
#
# IDT Accounts IDs can be found at https://github.com/coretech/infra-terra-commons/blob/master/aws/accounts.md
#
################################################################################################################
---
environments:
  qa:
    accountId: 542258342574

